# Generated by Django 5.2.9 on 2025-12-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedetection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='faces/'),
        ),
    ]
